# Enable colors and change prompt:
autoload -U colors && colors
PS1="%B%{$fg[red]%}[%{$fg[white]%}%n%{$fg[white]%}@%{$fg[white]%}%M %{$fg[cyan]%}%1~%{$fg[red]%}]%{$reset_color%}$%b "

# History
HISTFILE=~/.config/zsh/zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
setopt appendhistory

# Case insensitive tab completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
# setopt MENU_COMPLETE

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.

# git branch
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
RPROMPT='${vcs_info_msg_0_}'
zstyle ':vcs_info:git:*' formats ' %b'

WORDCHARS=${WORDCHARS/\//}

# C-w to delete word
ctrl-w-backward-delete-word() {
    zle backward-delete-word
}
zle -N ctrl-w-backward-delete-word
bindkey '^W' ctrl-w-backward-delete-word

#Use home and end to navigate terminal
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word

# Editor is nvim
EDITOR="/usr/bin/nvim"
NEOVIDE_MULTIGRID=1

# Path
export PATH=/home/ks/.local/bin:$PATH
export PATH=/home/ks/.cargo/bin:$PATH

# Aliases
alias ls="ls -h --color"
alias l="ls"
alias ll="ls -lh"
alias la="ls -lah"
alias ltr="ls -lahtr"
alias vim="nvim"
alias less="less -r -i"
alias xclip="xclip -selection c"
alias du-sort="du -h -d 1 | sort -h"

# Ranger quit in current directory
alias ranger='ranger --choosedir=$HOME/.cache/rangerdir; LASTDIR=`cat $HOME/.cache/rangerdir`; cd "$LASTDIR"'
alias r='ranger'

# yay shortcuts
alias fp="yay -Slq | fzf -m --preview 'yay -Si {1}' | yay -S -"
alias dp="yay -Slq | fzf -m --preview 'yay -Si {1}' | yay --getpkgbuild -"

# fzf for autocomplete
source /usr/local/opt/fzf/shell/key-bindings.zsh

# Load zsh-syntax-highlighting; should be last.
source /usr/local/opt/zsh-syntax-highlighting/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
